site_name: Trused AI

nav:
    - Home: 
        - Documentation: documentation.md
        - Introduction: introduction.md

    - Pillars: 
        - Fairness: Pillars/Fairness/index.md
        - Explainability: Pillars/Explainability.md
        - Robustness: Pillars/Robustness.md
        - Accountability : Pillars/Accountability/index.md
    - Tools:
        - IBM FactSheets 360: Tools/IBM-FactSheets/index.md
        - Another Tool: Tools/another-tool.md
    - Additional Aspects: Other_aspects.md
    - Code:
        - trusted AI algorithm: AI_algo.md
        - Implementation: code_documentation.md
    - References:
       - sources: sources.md


theme:
    name: readthedocs
    nav_style: dark

markdown_extensions:
    - attr_list
    - admonition
    - mdx_math
    - pymdownx.arithmatex :
        generic: true

extra_css:
    - extra.css
    - Pillars/Fairness/extra.css

extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
